FROM archlinux:base-devel

COPY pacman.conf /etc/pacman.conf
COPY init-image.bash /init-image.bash
RUN /init-image.bash

ADD <BINARY_URL> /usr/local/bin/build-pacman-repo
RUN chmod +x /usr/local/bin/build-pacman-repo

# force makepkg to allow running as root
RUN build-pacman-repo patch-makepkg --replace

COPY run.bash /run.bash

ENTRYPOINT ["/run.bash"]
